---
-   hosts: mc_server
    remote_user: "{{ user }}"

    tasks:
    -   name: execute the server
        shell: java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
        args:
            chdir: "{{ remote_mc_dir }}"
