---
-   name: Creates minecraft directory
    file:
        path: "{{ remote_mc_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ group }}"

-   name: download server.jar
    get_url:
        url: "{{ mc_dl_link }}"
        dest: "{{ remote_mc_dir }}/minecraft_server.jar"
        mode: a+x
        owner: "{{ user }}"
        group: "{{ group }}"

-   name: create eula.txt file to be able to execute the server
    template:
        src: eula.txt
        dest: "{{ remote_mc_dir }}/eula.txt"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ group }}"
